version: '3.8'

services:
  diploma:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./orders:/orders
    environment:
      - DB_HOST=database
      - DB_NAME=diploma
      - DB_USER=user2
      - DB_PASS=python123
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=diploma
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=python123
    restart: unless-stopped

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  celery_worker:
    build:
      context: .
    hostname: celery_worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./orders:/orders
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=diploma
      - DB_USER=user2
      - DB_PASS=python123
