POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
  "first_name": "Anatoly",
  "last_name": "Pakhomov",
  "email": "pythonist89@mail.ru",
  "password": "Testpassword12345",
  "password_confirm": "Testpassword12345",
  "company": "Netology",
  "position": "Developer"
}